### PR TITLE
add RE_SUB sqlite function to allow re.sub searches in db

### PR DESCRIPTION
**Pull request by wdduncan**

### CODE REVIEW

**Comment by wdduncan** [comment]
@EvgSkv It took me a while to get around to doing this, but as discussed in this [discussion](https://github.com/EvgSkv/logica/discussions/214), I added function for doing regex replace/sub.  I named it `RE_SUB` b/c it uses python's `re.sub`. I didn't name it `REGEX_REPLACE` b/c the parameters/behaviors of `re.sub` and `REGEX_REPLACE` are different enough that I didn't want to cause confusion.

However, I could figure how to test what I've added. For instance, do I have to recompile/build the logica libraries to access my function?

**Comment by EvgSkv** [comment]
@wdduncan thanks for working on this!

You can run your version of logica accessing this new function by simply running in logica's root folder:
```
python3 logica.py - run Q <<<'Q() = SqlExpr("RE_SUB({a}, {b}, {c})", {a: "abcdbcde", b:"b.", c:"X"})'
```

You can make this function available when SQLite engine is used by adding it here:
https://github.com/EvgSkv/logica/blob/main/compiler/dialect_libraries/sqlite_library.py

You can also add it to a test here:
https://github.com/EvgSkv/logica/blob/main/integration_tests/sqlite_funcs_test.l
For now tests are to be run manually as

```
python3 run_all_tests.py
```


Let me know if you have further questions.

**Comment by wdduncan** [comment]
Hi @EvgSkv . When I run
```
python3 logica.py - run Q <<<'Q() = SqlExpr("RE_SUB({a}, {b}, {c})", {a: "abcdbcde", b:"b.", c:"X"})'
```
I get error
```
BigQuery error in query operation: Cannot start a job without a project id.
```

I am not familiar with BigQuery (at all). Can I run w/o using BigQuery? I do have a GCloud account. But I have no idea how to pass a project id to logica :(

**Comment by EvgSkv** [comment]
@wdduncan 
oh, sorry my bad, you don't need BQ to test it.

I don't have the feature, so can't run it and couldn't test my code properly. I meant to write:
```
python3 logica.py - run Q <<<'@Engine("sqlite"); Q() = SqlExpr("RE_SUB({a}, {b}, {c})", {a: "abcdbcde", b:"b.", c:"X"})'
```

I apologize for delay with the response.

**Comment by wdduncan** [comment]
@EvgSkv Thanks for the command to test my feature. `RE_SUB` works, but you have to pass values in for the default arguments `count` and `flages`. In `RE_SUB`, `count` and `flags` are given default values of `0`.
```
  con.create_function('RE_SUB', 5, lambda string, pattern, repl="", count=0, flags=0: \
                                    re.sub(pattern, repl, string ,count, flags))
```
But, if you exclude them from the command:
```
python3 logica.py - run Q <<<'@Engine("sqlite"); Q() = SqlExpr("RE_SUB({a}, {b}, {c})", {a: "abcdbcde", b:"b.", c:"X"})'
````
You receive the error:
```
sqlite3.OperationalError: wrong number of arguments to function RE_SUB()
```


If you include the values for `count` and `flags`, it runs. I.e.:
```
python3 logica.py - run Q <<<'@Engine("sqlite"); Q() = SqlExpr("RE_SUB({a}, {b}, {c}, 0, 0)", {a: "abcdbcde", b:"b.", c:"X"})'

-->
+--------------+
| logica_value |
+--------------+
| aXdXde       |
+--------------+
```

I'm not sure if the ignoring of the default values is due to logica or python's `create_function`.  Do you know?

**Comment by wdduncan** [comment]
@EvgSkv Just checking in ... are going to merge the PR?

**Comment by EvgSkv** [comment]
Hi @wdduncan !
Sorry about delay, I got myself distracted. The PR looks great, I merged it in! Thank you for the contribution!

FYI, I found this answer:
https://stackoverflow.com/questions/71245367/how-to-create-a-user-defined-sqlite-function-with-optional-arguments

So we may remove constraint on the number of arguments if it helps.

**Comment by wdduncan** [comment]
Thanks @EvgSkv !!!

**Pull request merged**
