### PR TITLE
Allow import_root specification to be a list.

### PR DESCRIPTION
**Pull request by EvgSkv**

### CODE REVIEW

**Comment by mhfrantz** [comment]
LGTM

This addresses our use case. We would use `sys.path` for `import_root` when invoked from Python, and `PYTHONPATH` for `LOGICAPATH` from the CLI.

**Comment by EvgSkv** [comment]
Okay, great! Thanks for checking.
I'll merge the request and will push update to pypi later today.

**Comment by jesseagreene** [comment]
@EvgSkv Any chance you could push an update to pypi?

**Comment by EvgSkv** [comment]
> @EvgSkv Any chance you could push an update to pypi?

Sure! Done (version 1.3.14.15.92). Let me know if it has any problems!

**Pull request merged**
